server:
  port: 9001
  servlet:
    context-path: /imooc

spring:
  application:
    name: e-commerce-gateway
  cloud:
    nacos:
      discovery:
        enabled: true # 如果不想使用 Nacos 进行服务注册和发现, 设置为 false 即可
        server-addr: 192.168.137.10:8848 # Nacos 服务器地址
        # server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850 # Nacos 服务器地址
        namespace: 5a17d9a0-e2bb-490d-9a59-b4218c1e3751
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    sender:
      type: rabbit
    base-url: http://localhost:9411/



#    静态路由
#    gateway:
#      routes:
#        - id: path_route # 路由的ID
#          uri: 127.0.0.1:8080/user/{id} # 匹配后路由地址
#          predicates: # 断言, 路径相匹配的进行路由
#            - Path=/user/{id}


# 这个地方独立配置, 是网关的数据, 代码 GatewayConfig.java 中读取被监听
nacos:
  gateway:
    route:
      config:
        data-id: e-commerce-gateway-router
        group: e-commerce