### 查询服务
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?service-id=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIlFpbnlpQGltb29jLmNvbVwifSIsImp0aSI6ImQyZjIzNDZjLWVkN2MtNGQ2OC1iZDYwLWY5YmM0ZTk5Zjk2YSIsImV4cCI6MTY2NzIzMjAwMH0.TK9MYF1mF8tlfKQe-xRkTaboW7I5UY51aaMnRIjiwa-ii9c_5y9cJgyYUmzIA40qOdDxR401yw6vcCsb8wasj0cniC-KYlGH0_5mvVLYIJI9yESoZM7Rtdsjx89yBDyETwzJdO0RvuOfvcmCS28GSZoZzwQ0H3I3zL-mDlzQwjkDUbPjh7HwRSjMqz7Ofyr637-UxoUol63r1oIF4XvOtMx_Ghn7Fp_3XRqewsuVFde4sN6j7ANjw4F9VzTo2msOe24FGmgSE02K9nQ1IVBAB8Iu5RElri5ZPFCHXsK5YYQWfE4DrLbhBpASVCtVRiQLdt-CPCUr035keYYQFk2htg
token: imooc

### 查询服务
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/sleuth/trace-info
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIlFpbnlpQGltb29jLmNvbVwifSIsImp0aSI6ImQyZjIzNDZjLWVkN2MtNGQ2OC1iZDYwLWY5YmM0ZTk5Zjk2YSIsImV4cCI6MTY2NzIzMjAwMH0.TK9MYF1mF8tlfKQe-xRkTaboW7I5UY51aaMnRIjiwa-ii9c_5y9cJgyYUmzIA40qOdDxR401yw6vcCsb8wasj0cniC-KYlGH0_5mvVLYIJI9yESoZM7Rtdsjx89yBDyETwzJdO0RvuOfvcmCS28GSZoZzwQ0H3I3zL-mDlzQwjkDUbPjh7HwRSjMqz7Ofyr637-UxoUol63r1oIF4XvOtMx_Ghn7Fp_3XRqewsuVFde4sN6j7ANjw4F9VzTo2msOe24FGmgSE02K9nQ1IVBAB8Iu5RElri5ZPFCHXsK5YYQWfE4DrLbhBpASVCtVRiQLdt-CPCUr035keYYQFk2htg
token: imooc