### 查询服务
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?service-id=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjExLFwidXNlcm5hbWVcIjpcIlFpbnlpQGltb29jLmNvbVwifSIsImp0aSI6IjFiYTQ3ZTYxLTQ3OGItNDcxNS04OWMyLTczZmNlNWIwYWIzNiIsImV4cCI6MTY2MzI1NzYwMH0.SWc8jKhYLmPD0dyW-4wBjB3OXZXjOkYvcQB-Gg4lIZnnAogVUt_wZZ52JGFI740MRi0oJKEpU1lzRVEob7E21D0LchQvFrtcDl-6Wff9JQ0HBMeI_b4w5UDPVHf21ev4vg83pGN1V5rtdrSRhxlm87nNRUVsyst_QqcWLkl-0GzAYDJj5IweJMrIhba6Yc25pi5gHHtNDXPpSaHQjxUcd1bZuLF2PYiRL4_PouR_KbIUbNBaDTrRv02drdFCLKcpJTxohBoD2rhtdqZWcFaES2_8r8DFFSpgA25SoJPqKorbDUiglSq8rZbdOOBDJeTy6xfqQw0fKrzHphdCdGdDvw
token: imooc

### 查询服务
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/sleuth/trace-info
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjExLFwidXNlcm5hbWVcIjpcIlFpbnlpQGltb29jLmNvbVwifSIsImp0aSI6IjEyMGNhZmZlLTMyMWUtNGJlMS1iMzIyLTJkY2UxMjVjOThkMSIsImV4cCI6MTY2MzE3MTIwMH0.QnyG-nNyGzfOLRLc6u_E16VOcYiP5ENe-OwHQhHcBEVb0ZGPReJ6BriKrtHwtoNOMA6lTa4k-jiyYZrqDN7LpOuGst6FC8X1dbgX4eKfugzk5QXLAvhbR6WLR8i9_hkjN5PI1XO9UoLWYbIN9J5f1sDZ7R-xwoVHdyfcGOTFqupBnD8yqeKBJR2UxhY_he4Tm6k1G_47nZpFie4duZD03YClmvbBlvJYx2uLl9DEhZvQEG66LL9TpLG8WMkCgaEq7uTo2W3Ozj6DHHfEGYpMiuz89VrReWiKADqRe5KLiW7bNK8lJmtiNAqfZTu6kkBgbphHyZhSP8tr44V93I-NQg
token: imooc