### 查询服务
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance?service-id=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEyLFwidXNlcm5hbWVcIjpcIkltb29jUWlueWlAaW1vb2MuY29tXCJ9IiwianRpIjoiMjY2OTM5YWMtODNiMy00NzAzLWI4ODEtN2U2M2YyYzY0ZTA3IiwiZXhwIjoxNjYzMDg0ODAwfQ.fyY_s3ExouJOJn2ksVwDs9H-3azpqIEsiPzPwWmlD1QBxR5nED7fymU2uNKwJmIckYa7cYUzW0iFs6R1SxmJvRA4fPlAY3iXaDO1btCkSR6AR4FhF8eIe4eZ36gpAcEpMoSVGDnJj8hoYQ4Vtqg-AIQeGbCUnRC8agoII4JqIc79Qk7Di4AidezXaYKdfTOa6ApC67hfeatC4MX5tx65VsR7H9xq--9l7vIMFd-HsaR7brMo9exxgodLXp9yBMtUW0CCKPVdzV609TWqB2Jdsl7yrVJu2E8XztlptXF4jKvBDg-Xeg8heJekLgAEdUfnXrTaZT3vbNkYVpI0u5adHQ
token: imooc