server:
  port: 8000
  servlet:
    context-path: /ecommerce-nacos-client

spring:
  application:
    name: e-commerce-nacos-client
  cloud:
    nacos:
      # 服务注册发现
      discovery:
        # 如果不想使用 Nacos 进行服务注册和发现, 设置为 false 即可
        enabled: true
        namespace: 5a17d9a0-e2bb-490d-9a59-b4218c1e3751
        server-addr: 192.168.137.10:8848
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
      config:
        server-addr: 192.168.137.10:8848
        file-extension: yaml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    sender:
      type: rabbit
    base-url: http://localhost:9411/

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always