server:
  port: 7001
  servlet:
    context-path: /e-commerce-admin

spring:
  application:
    name: e-commerce-admin
  security:
    user:
      name: admin
      password: admin
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.137.20:8848
        namespace: 5a17d9a0-e2bb-490d-9a59-b4218c1e3751
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
          user:
            name: admin
            password: admin

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 *, 可以开放所有端点
  endpoint:
    health:
      show-details: always